# Generated by Django 4.2.27 on 2025-12-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='per_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
