# Generated by Django 4.2.27 on 2025-12-12 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_income', models.FloatField()),
                ('coapplicant_income', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_amount_term', models.FloatField(default=360)),
                ('credit_history', models.FloatField()),
                ('property_area', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('employment', models.CharField(max_length=50)),
                ('prediction', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
